file-name-convention:

  # Reference to files at your behavior pack folder
  behavior_pack:
    animation_controllers: '.animation_controllers.json'
    animations: '.animation.json'
    biomes: '.biome.json'
    blocks: '.block.json'
    dialogue: '.dialogue.json'
    entities: '.behavior.json'
    features: '.feature.json'
    feature_rules: '.feature_rule.json'
    items: '.item.json'
    loot_tables: '.loot_table.json'
    recipes: '.recipe.json'
    spawn_rules: '.spawn_rule.json'
    trading: '.trade.json'

  # Reference to files at your resource pack folder
  resource_pack:
    animation_controllers: '.animation_controllers.json'
    animations: '.animation.json'
    attachables: '.attachable.json'
    entity: '.entity.json'
    fog: '.fog_setting.json'
    models: '.geo.json'
    items: '.item.json'
    particles: '.particle.json'
    render_controllers: '.render_controllers.json'

# The patterns are defined globally, that is, the pattern defined
# for 'animations' will serve both for resource pack and for behavior pack.
name-patterns:
  identifiers: '^(?:(?:(?!minecraft|minecon))+[a-z]*:[a-z_]*)+$'
  animation_controllers: '^(?:controller.animation.)+[a-z0-9_.]+$'
  animations: '^(?:animation.)+[a-z0-9_.]+$'
  geometries: '^(?:geometry.)+[a-z_]+$'
