name: 'loom-action'
description: 'Standardization and moderation when creating addons for Minecraft Bedrock.'
author: Leonardo Luiz Gava

branding:
  icon: 'box'
  color: 'green'

inputs:
  pattern:
    required: true
    default: 'mojang'
    description: 'The file endings style.'

  silent:
    required: true
    default: false
    description: 'If true, no progress log will be showed. Only errors.'

  behavior_pack_path:
    required: false
    default: 'behavior_packs/0'
    description: 'The relative path to behavior pack folder.'

  resource_pack_path:
    required: false
    default: 'resource_packs/0'
    description: 'The relative path to resource pack folder.'

runs:
  using: 'node16'
  main: 'dist/index.js'
